---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wot.ninjatec.co.uk
  namespace: emissary
spec:
  hostname: wot.ninjatec.co.uk 
  acmeProvider: 
    authority: none
  tlsSecret:
    name: ambassador-certs
  tlsContext:
    name: tls-context-wot
  requestPolicy:
    insecure:
      action: Redirect

---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: www.ninjatec.co.uk
  namespace: emissary
spec:
  hostname: www.ninjatec.co.uk 
  acmeProvider: 
    authority: none
  tlsSecret:
    name: ambassador-certs
  tlsContext:
    name: tls-context-wot
  requestPolicy:
    insecure:
      action: Redirect

---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: www.workouttracker.online
  namespace: emissary
spec:
  hostname: www.workouttracker.online
  acmeProvider:
    authority: none
  tlsSecret:
    name: ambassador-certs-workouttracker
  tlsContext:
    name: tls-context-workouttracker
  requestPolicy:
    insecure:
      action: Redirect

---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: workouttracker.online
  namespace: emissary
spec:
  hostname: workouttracker.online
  acmeProvider:
    authority: none
  tlsSecret:
    name: ambassador-certs-workouttracker
  tlsContext:
    name: tls-context-workouttracker
  requestPolicy:
    insecure:
      action: Redirect

---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: tls-context-wot
  namespace: emissary
spec:
  alpn_protocols: h2,http/1.1
  hosts:
  - wot.ninjatec.co.uk
  - www.ninjatec.co.uk
  secret: ambassador-certs
  secret_namespacing: false
  min_tls_version: v1.2
  cipher_suites:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305

---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: tls-context-workouttracker
  namespace: emissary
spec:
  alpn_protocols: h2,http/1.1
  hosts:
  - www.workouttracker.online
  - workouttracker.online
  secret: ambassador-certs-workouttracker
  secret_namespacing: false
  min_tls_version: v1.2
  cipher_suites:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305

---
apiVersion: getambassador.io/v3alpha1
kind: KubernetesEndpointResolver
metadata:
  name: kubernetes-endpoint
  namespace: emissary