---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ambassador-certs-workouttracker
  namespace: emissary
spec:
  secretName: ambassador-certs-workouttracker
  dnsNames:
  - www.workouttracker.online
  - workouttracker.online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer