apiVersion: apps/v1
kind: Deployment
metadata:
  name: workouttracker
  namespace: web
  labels:
    app: workouttracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workouttracker
  template:
    metadata:
      labels:
        app: workouttracker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: workouttracker
        image: ninjatec/workouttrackerweb:latest
        ports:
        - containerPort: 80