apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workouttracker-tempo
  namespace: web
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: workouttracker-tempo-secrets
    template:
      type: Opaque
  data:
    - secretKey: OTLP_ENDPOINT
      remoteRef:
        key: workouttracker/tempo
        property: endpoint
    - secretKey: OTEL_AUTH_BEARER
      remoteRef:
        key: workouttracker/tempo
        property: bearer_token
