---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: workouttracker
  namespace: web
spec:
  hostname: wot.ninjatec.co.uk
  prefix: /
  service: workouttracker.web:80
  allow_upgrade:
  - websocket
  resolver: kubernetes-endpoint
  load_balancer:
    policy: ring_hash
    cookie:
      name: emissary-sticky-cookie
      ttl: 7200s

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: workouttrackeronline
  namespace: web
spec:
  hostname: www.workouttracker.online
  prefix: /
  service: workouttracker.web:80
  allow_upgrade:
  - websocket
  resolver: kubernetes-endpoint
  load_balancer:
    policy: ring_hash
    cookie:
      name: emissary-sticky-cookie
      ttl: 7200s