apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: web
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
spec:
  selector:
    statefulset.kubernetes.io/pod-name: redis-node-0
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  type: ClusterIP
