---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecs-workouttracker-secrets
  namespace: web
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: workouttracker-secrets
    creationPolicy: Owner
  data:
  - secretKey: EmailSettings__SenderName
    remoteRef:
      key: secrets/workouttracker-secrets
      property: EmailSettings__SenderName

  - secretKey: EmailSettings__SenderEmail
    remoteRef:
      key: secrets/workouttracker-secrets
      property: EmailSettings__SenderEmail

  - secretKey: EmailSettings__UserName
    remoteRef:
      key: secrets/workouttracker-secrets
      property: EmailSettings__UserName

  - secretKey: EmailSettings__MailServer
    remoteRef:
      key: secrets/workouttracker-secrets
      property: EmailSettings__MailServer

  - secretKey: EmailSettings__MailPort
    remoteRef:
      key: secrets/workouttracker-secrets
      property: EmailSettings__MailPort

  - secretKey: EmailSettings__Password
    remoteRef:
      key: secrets/workouttracker-secrets
      property: EmailSettings__Password

  - secretKey: EmailSettings__UseSsl
    remoteRef:
      key: secrets/workouttracker-secrets
      property: EmailSettings__UseSsl

  - secretKey: ConnectionStrings__WorkoutTrackerWebContext
    remoteRef:
      key: secrets/workouttracker-secrets
      property: ConnectionStrings__WorkoutTrackerWebContext

  - secretKey: ConnectionStrings__DefaultConnection
    remoteRef:
      key: secrets/workouttracker-secrets
      property: ConnectionStrings__DefaultConnection
      
  - secretKey: ApiKeys__ApiNinjas
    remoteRef:
      key: secrets/workouttracker-secrets
      property: ApiKeys__ApiNinjas

  - secretKey: OTLP_ENDPOINT
    remoteRef:
      key: secrets/workouttracker-secrets
      property: OTLP_ENDPOINT

  - secretKey: OTEL_AUTH_BEARER
    remoteRef:
      key: secrets/workouttracker-secrets
      property: OTEL_AUTH_BEARER
  
  - secretKey: ConnectionStrings__Redis
    remoteRef:
      key: secrets/workouttracker-secrets
      property: ConnectionStrings__Redis

