apiVersion: v1
kind: Service
metadata:
  name: workouttracker
  namespace: web
spec:
  selector:
    app: workouttracker
  type: ClusterIP
  ports:
    - name: httpport
      port: 80
      targetPort: 8080
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300