name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Publish and Deploy
        run: |
          chmod +x ./scripts/publish_to_prod.sh
          ./scripts/publish_to_prod.sh

      - name: Push changes (if any)
        run: |
          git config user.name "Marc Coxall"
          git config user.email "marc.coxall@ninjatec.co.uk"
          git add .
          git commit -m "CI: Update k8s manifests and version after deploy" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
